[build-system]
requires = ["scikit-build-core", "meson", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "mobbrmsd"

dependencies = [
    "numpy",
    "matplotlib",
    "networkx",
    "tqdm",
    "pick",
    "mdtraj",
]

version = "0.0.27"

description = "Molecular-Oriented RMSD with Branch-and-Bound"

readme = "README.md"

license = {file = "LICENSE.txt"}

requires-python = ">=3.8"

authors = [
    {name = "yymmt742", email = "yymmt@kuchem.kyoto-u.ac.jp"}
]

maintainers = [
    {name = "yymmt742", email = "yymmt@kuchem.kyoto-u.ac.jp"}
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.optional-dependencies]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
]

[tool.scikit-build]
ninja.version = ">=1.10"
cmake.version = ">=3.14"
