[build-system]
requires = ["scikit-build-core", "numpy", "networkx", "matplotlib", "pick", "tqdm"]
build-backend = "scikit_build_core.build"

[project]
name = "mobbrmsd"
dependencies = ["numpy"]
version = 0.0.22.8
readme = "README.md"
license = {file = "LICENSE.txt"}

[tool.scikit-build]
version = 0.0.22.8
version = 0.0.22.8
