name: CI

on: [push, pull_request]

env:
  CMAKE_BUILD_PARALLEL_LEVEL: "2" # 2 cores on each GHA VM, enable parallel builds
  CTEST_OUTPUT_ON_FAILURE: "ON" # This way we don't need a flag to ctest
  CTEST_PARALLEL_LEVEL: "2"
  CTEST_TIME_TIMEOUT: "5"  # some failures hang forever
  HOMEBREW_NO_ANALYTICS: "ON" # Make Homebrew installation a little quicker
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain:
          - {compiler: gcc, version: 12}
          - {compiler: intel, version: '2023.2'}
          - {compiler: nvidia-hpc, version: '24.5'}
        exclude:
          - os: macos-latest
            toolchain: {compiler: intel, version: '2023.2'}
          - os: macos-latest
            toolchain: {compiler: nvidia-hpc, version: '24.5'}
          - os: windows-latest
            toolchain: {compiler: nvidia-hpc, version: '24.5'}
          - os: windows-latest
            toolchain: {compiler: intel, version: '2023.2'}

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # コードを取得
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5 # Python環境のセットアップ
        with:
          python-version: "3.*"

      - name: Setup fortran
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Install cmake and fypp
        run: pip install --upgrade cmake fypp

      - name: Configure with CMake (windows)
        if: contains(matrix.os, 'windows')
        run: >-
          cmake -Wdev
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_INSTALL_PREFIX=_dist
          -G "MinGW Makefiles"
          -S . -B build

      - name: Configure with CMake (UNIX)
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
        run: >-
          cmake -Wdev
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_INSTALL_PREFIX=_dist
          -S . -B build

      - name: Build and compile
        run: cmake --build build

      - name: catch build fail
        if: ${{ failure() }}
        run: cmake --build build --verbose

      - name: test
        run: >-
          ctest
          --test-dir build
          --parallel
          --output-on-failure
          --no-tests=error

      - name: Install project
        run: cmake --install build
