name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: '作成するバージョンを入力してください'
        required: true

permissions:
  contents: write
  id-token: write

jobs:

  build:
    name: Build distribution
    runs-on: ubuntu-latest

    env:
      # githubのコンソールから入力したリリース名を環境変数へ保存
      VERSION_STRING: ${{ github.event.inputs.version }}
      RELEASE_BRANCH_NAME: release/${{ github.event.inputs.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4 # コードを取得

    - name: Create and push release branch # releaseブランチを作成
      run:
        git checkout -b ${{ env.RELEASE_BRANCH_NAME }}

    - name: Set up Python
      uses: actions/setup-python@v5 # Python環境のセットアップ
      with:
        python-version: "3.*"

    - name: Setup Fortran
      uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: gcc
        version: 12

    - name: Install pypa/build # ビルドツールをインストール
      run: >-
        python -m
        pip install
        build
        meson
        --user

    - name: Build a binary wheel and a source tarball # パッケージをビルド
      run: python -m build

    - name: Store the distribution packages # ビルド成果物をpython-package-distributionsという名前でdistディレクトリに一時的に保存
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Update pyproject.toml
      shell: bash
      run: sed -i '/^version =/c version = "${{ env.VERSION_STRING }}"' pyproject.toml

    - name: Commit pyproject.toml
      uses: EndBug/add-and-commit@v7.1.0
      with:
        author_name: "yymmt742"
        author_email: "yymmt@kuchem.kyoto-u.ac.jp"
        message: "[update] pyproject.toml, version"
        add: pyproject.toml

    - name: Create a tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        custom_tag: ${{ env.VERSION_STRING }}
        tag_prefix: v
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v2.1.1
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --notes ""

    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release upload
        '${{ github.ref_name }}' dist/**
        --repo '${{ github.repository }}'

